// Arabic labels for audit-log events (jahez_api app/Enums/AuditEvent.php). The VALUES come from the API;
// only their display text lives here. An event the API adds later is shown with its raw name.

export const AUDIT_EVENTS: Record<string, string> = {
  'auth.login_succeeded': 'تسجيل دخول ناجح',
  'auth.login_failed': 'محاولة دخول فاشلة',
  'auth.login_throttled': 'تقييد محاولات الدخول',
  'auth.logged_out': 'تسجيل خروج',
  'auth.password_reset_requested': 'طلب استعادة كلمة المرور',
  'auth.password_reset_completed': 'تعيين كلمة مرور جديدة',
  'user.created': 'إنشاء حساب',
  'user.renamed': 'تعديل اسم حساب',
  'user.deactivated': 'إيقاف حساب',
  'user.reactivated': 'إعادة تفعيل حساب',
  'user.administrator_created_from_console': 'إنشاء مدير من سطر الأوامر',
  'factory.created': 'إنشاء منشأة',
  'factory.registered': 'تسجيل منشأة ذاتيًا',
  'factory.updated': 'تعديل منشأة',
  'factory.approval_changed': 'قرار اعتماد منشأة',
  'factory.review_requested': 'طلب منشأة مراجعة جديدة',
  'factory.change_request_submitted': 'طلب تعديل بيانات قانونية لمنشأة',
  'factory.change_request_approved': 'اعتماد تعديل بيانات قانونية لمنشأة',
  'factory.change_request_rejected': 'رفض تعديل بيانات قانونية لمنشأة',
  'factory.change_request_cancelled': 'إلغاء طلب تعديل بيانات منشأة',
  'factory.assessment_recorded': 'تصنيف يدوي سابق',
  'factory.readiness_assessment_completed': 'اكتمال تقييم جاهزية رقمية',
  'readiness_questionnaire.drafted': 'إنشاء مسودة استبيان',
  'readiness_questionnaire.updated': 'تعديل مسودة استبيان',
  'readiness_questionnaire.published': 'نشر إصدار استبيان',
  'readiness_questionnaire.deleted': 'حذف مسودة استبيان',
  'service_provider.created': 'إنشاء مزود خدمة',
  'service_provider.registered': 'تسجيل مزود خدمة ذاتيًا',
  'service_provider.updated': 'تعديل مزود خدمة',
  'service_provider.approval_changed': 'قرار اعتماد مزود',
  'service_provider.review_requested': 'طلب مراجعة جديدة',
  'service_provider.evaluation_recorded': 'تسجيل تقييم فني',
  'service_provider.change_request_submitted': 'طلب تعديل بيانات قانونية لمزود',
  'service_provider.change_request_approved': 'اعتماد تعديل بيانات قانونية لمزود',
  'service_provider.change_request_rejected': 'رفض تعديل بيانات قانونية لمزود',
  'service_provider.change_request_cancelled': 'إلغاء طلب تعديل بيانات مزود',
  'service_listing.reviewed': 'قرار اعتماد خدمة مزود',
  'organization.document_uploaded': 'رفع مستند',
  'agreement.reviewed': 'قرار المركز على اتفاقية',
  'promotion.created': 'إنشاء إعلان',
  'promotion.updated': 'تعديل إعلان',
  'promotion.ended': 'إنهاء إعلان',
  'service_request.created': 'إنشاء طلب خدمة',
  'service_request.cancelled': 'إلغاء طلب خدمة',
  'service_request.providers_added': 'إضافة مزودين إلى طلب',
  'provider_request.accepted': 'قبول مزود للطلب',
  'provider_request.declined': 'اعتذار مزود عن الطلب',
  'provider_request.withdrawn': 'سحب الطلب من مزود',
  'offer.submitted': 'تقديم عرض',
  'offer.accepted': 'قبول عرض',
  'agreement.concluded': 'إبرام اتفاقية',
  'contract.drafted': 'إعداد مسودة عقد',
  'contract.cancelled': 'إلغاء مسودة عقد',
  'invoice.drafted': 'إعداد مسودة فاتورة',
  'invoice.issued': 'إصدار فاتورة',
  'invoice.cancelled': 'إلغاء فاتورة',
  'payment.initiated': 'بدء عملية دفع',
  'payment.status_changed': 'تغيّر حالة دفعة',
};

export const auditEventLabel = (event: string): string => AUDIT_EVENTS[event] ?? event;

export const SUBJECT_TYPES: { value: 'user' | 'factory' | 'service_provider'; label: string }[] = [
  { value: 'user', label: 'حساب مستخدم' },
  { value: 'factory', label: 'منشأة' },
  { value: 'service_provider', label: 'مزود خدمة' },
];

export const subjectTypeLabel = (type: string): string => SUBJECT_TYPES.find((s) => s.value === type)?.label ?? type;
